import { issue, htmlPages, groupBy } from './issue.js';

const norm = s => (s || '').toLowerCase().replace(/[^\p{L}\p{N}\s]/gu, ' ').replace(/\s+/g, ' ').trim();

export function commonSuffix(titles) {
  const counts = new Map();
  titles.forEach(t => { const m = t.match(/\s[|\-–—:·•]\s(.{2,60})$/); if (m) counts.set(m[1], (counts.get(m[1]) || 0) + 1); });
  const best = [...counts.entries()].sort((a, b) => b[1] - a[1])[0];
  return best && best[1] >= Math.max(2, titles.length * 0.3) ? best[0] : null;
}

export function analyzeOnPage(ctx) {
  const { pages, homeUrl } = ctx; const issues = [];
  const html = htmlPages(pages).filter(p => !p.data.robots.noindex); const total = html.length || 1;
  const add = (o) => { if (o.evidence.length) issues.push(issue({ category: 'onpage', totalPages: total, ...o })); };
  const titles = html.map(p => p.data.title).filter(Boolean);
  const brand = commonSuffix(titles);

  // Titles
  add({ id: 'title-missing', severity: 'high', title: 'Pages missing a title tag', evidence: html.filter(p => !p.data.title).map(p => ({ url: p.finalUrl, detail: p.data.titleTagCount ? 'Title tag is empty' : 'No <title> element' })), why: 'The title is the main clickable headline in search results and a strong relevance signal.', fix: 'Write a unique title that leads with the page topic.' });
  add({ id: 'title-multiple', severity: 'low', title: 'Pages with more than one title tag', evidence: html.filter(p => p.data.titleTagCount > 1).map(p => ({ url: p.finalUrl, detail: `${p.data.titleTagCount} title tags` })), why: 'Search engines may pick the wrong one.', fix: 'Output a single title tag (check theme and SEO plugin overlap).' });
  add({ id: 'title-short', severity: 'low', title: 'Title tags under 30 characters', evidence: html.filter(p => p.data.title && p.data.title.length < 30).map(p => ({ url: p.finalUrl, detail: `${p.data.title.length} chars: "${p.data.title}"` })), why: 'Very short titles miss descriptive terms that match searches.', fix: 'Add the specific topic, qualifier or location.' });
  add({ id: 'title-long', severity: 'low', title: 'Title tags over 60 characters', evidence: html.filter(p => p.data.title && p.data.title.length > 60).map(p => ({ url: p.finalUrl, detail: `${p.data.title.length} chars: "${p.data.title}"` })), why: 'Google typically truncates titles around 600 pixels (about 55 to 60 characters).', fix: 'Front load the key topic and trim filler.' });
  const dupTitles = [...groupBy(html.filter(p => p.data.title), p => p.data.title.toLowerCase()).values()].filter(g => g.length > 1);
  add({ id: 'title-duplicate', severity: 'medium', title: 'Duplicate title tags', evidence: dupTitles.flatMap(g => g.map(p => ({ url: p.finalUrl, detail: `"${p.data.title}" shared by ${g.length} pages` }))), why: 'Identical titles make pages compete with each other and hide what makes each unique.', fix: 'Give every page a title describing its specific content.' });
  if (brand) {
    const dupStripped = [...groupBy(html.filter(p => p.data.title), p => norm(p.data.title.replace(brand, '').replace(/[|\-–—:·•]\s*$/, ''))).values()].filter(g => g.length > 1 && new Set(g.map(p => p.data.title)).size > 1);
    add({ id: 'title-near-duplicate', severity: 'low', title: 'Titles that differ only by brand or separator', evidence: dupStripped.flatMap(g => g.map(p => ({ url: p.finalUrl, detail: p.data.title }))), why: 'Near duplicate titles signal overlapping pages.', fix: 'Differentiate the topic part of the title.' });
  }
  add({ id: 'title-h1-mismatch', severity: 'low', title: 'Title and H1 share no words', evidence: html.filter(p => p.data.title && p.data.h1s[0]).filter(p => { const t = new Set(norm(p.data.title).split(' ').filter(w => w.length > 3)); return !norm(p.data.h1s[0]).split(' ').some(w => t.has(w)); }).map(p => ({ url: p.finalUrl, detail: `Title "${p.data.title}" / H1 "${p.data.h1s[0]}"` })), why: 'Aligned title and H1 reinforce what the page is about.', fix: 'Use the same core topic in both.' });

  // Meta descriptions
  add({ id: 'meta-missing', severity: 'medium', title: 'Pages missing a meta description', evidence: html.filter(p => !p.data.metaDescription).map(p => ({ url: p.finalUrl, detail: p.data.title ? `Has title "${p.data.title}" but no description` : 'No description' })), why: 'Without one, Google builds a snippet from page text, which often reads poorly and lowers click through.', fix: 'Write a 120 to 155 character summary with a clear reason to click.' });
  add({ id: 'meta-short', severity: 'low', title: 'Meta descriptions under 70 characters', evidence: html.filter(p => p.data.metaDescription && p.data.metaDescription.length < 70).map(p => ({ url: p.finalUrl, detail: `${p.data.metaDescription.length} chars` })), why: 'Short descriptions waste snippet space.', fix: 'Expand with benefits, specifics or a call to action.' });
  add({ id: 'meta-long', severity: 'low', title: 'Meta descriptions over 160 characters', evidence: html.filter(p => p.data.metaDescription && p.data.metaDescription.length > 160).map(p => ({ url: p.finalUrl, detail: `${p.data.metaDescription.length} chars` })), why: 'Long descriptions get truncated.', fix: 'Keep the key message in the first 150 characters.' });
  const dupMeta = [...groupBy(html.filter(p => p.data.metaDescription), p => p.data.metaDescription.toLowerCase()).values()].filter(g => g.length > 1);
  add({ id: 'meta-duplicate', severity: 'low', title: 'Duplicate meta descriptions', evidence: dupMeta.flatMap(g => g.map(p => ({ url: p.finalUrl, detail: `Shared by ${g.length} pages` }))), why: 'Duplicate descriptions are usually ignored and replaced by Google.', fix: 'Write unique descriptions for key pages.' });
  add({ id: 'meta-multiple', severity: 'low', title: 'Multiple meta description tags', evidence: html.filter(p => p.data.metaDescriptions.length > 1).map(p => ({ url: p.finalUrl, detail: `${p.data.metaDescriptions.length} tags` })), why: 'Conflicting tags make the snippet unpredictable.', fix: 'Output one meta description.' });

  // Headings
  add({ id: 'h1-missing', severity: 'medium', title: 'Pages without an H1', evidence: html.filter(p => !p.data.h1s.filter(Boolean).length).map(p => ({ url: p.finalUrl, detail: p.data.h1s.length ? 'H1 is empty' : 'No H1' })), why: 'The H1 tells users and search engines the main topic of the page.', fix: 'Add one descriptive H1 near the top of the content.' });
  add({ id: 'h1-multiple', severity: 'low', title: 'Pages with multiple H1s', evidence: html.filter(p => p.data.h1s.length > 1).map(p => ({ url: p.finalUrl, detail: p.data.h1s.slice(0, 3).map(h => `"${h}"`).join(', ') })), why: 'Not an error for Google, but often reveals a logo or template element tagged as H1.', fix: 'Keep a single H1 for the main topic; use H2 for sections.' });
  const dupH1 = [...groupBy(html.filter(p => p.data.h1s[0]), p => p.data.h1s[0].toLowerCase()).values()].filter(g => g.length > 1);
  add({ id: 'h1-duplicate', severity: 'low', title: 'Duplicate H1 across pages', evidence: dupH1.flatMap(g => g.map(p => ({ url: p.finalUrl, detail: `"${p.data.h1s[0]}" on ${g.length} pages` }))), why: 'Same H1 on multiple pages suggests template headings or overlapping topics.', fix: 'Write page specific H1s.' });
  add({ id: 'h1-long', severity: 'low', title: 'Very long H1s (over 70 characters)', evidence: html.filter(p => p.data.h1s[0]?.length > 70).map(p => ({ url: p.finalUrl, detail: `${p.data.h1s[0].length} chars` })), why: 'Long headings dilute the main topic.', fix: 'Tighten the heading to the core topic.' });
  add({ id: 'heading-skip', severity: 'low', title: 'Heading levels skip (for example H2 to H4)', evidence: html.filter(p => p.data.headings.some((h, i, a) => i > 0 && h.level - a[i - 1].level > 1)).map(p => { const h = p.data.headings; const i = h.findIndex((x, j) => j > 0 && x.level - h[j - 1].level > 1); return { url: p.finalUrl, detail: `H${h[i - 1].level} "${h[i - 1].text.slice(0, 40)}" followed by H${h[i].level}` }; }), why: 'A logical outline helps accessibility tools and makes sections easier to extract.', fix: 'Use heading levels in order without gaps.', effort: 'low' });
  add({ id: 'heading-empty', severity: 'low', title: 'Empty heading tags', evidence: html.filter(p => p.data.headings.some(h => !h.text)).map(p => ({ url: p.finalUrl, detail: `${p.data.headings.filter(h => !h.text).length} empty headings` })), why: 'Empty headings add noise to the document outline.', fix: 'Remove them or add text.' });

  // Social
  add({ id: 'og-missing', category: 'social', severity: 'low', title: 'Pages missing Open Graph title, description or image', evidence: html.filter(p => !p.data.og.title || !p.data.og.image || !p.data.og.description).map(p => ({ url: p.finalUrl, detail: ['title', 'description', 'image'].filter(k => !p.data.og[k]).map(k => 'og:' + k).join(', ') + ' missing' })), why: 'Links shared on social and chat apps show a blank or random preview.', fix: 'Set og:title, og:description and og:image (1200x630) for each page.' });
  add({ id: 'twitter-card-missing', category: 'social', severity: 'low', title: 'Pages without a Twitter/X card', evidence: html.filter(p => !p.data.twitter.card).map(p => ({ url: p.finalUrl, detail: 'No twitter:card' })), why: 'X falls back to Open Graph but a card type controls the large image preview.', fix: 'Add twitter:card summary_large_image.' });

  // Images (alt and markup)
  const imgs = html.flatMap(p => p.data.images.map(i => ({ ...i, page: p.finalUrl })));
  add({ id: 'img-alt-missing', severity: 'medium', title: 'Images missing alt attributes', evidence: imgs.filter(i => !i.hasAlt && i.src).map(i => ({ url: i.page, detail: i.src })), why: 'Alt text is how image search and screen readers understand images.', fix: 'Describe meaningful images; use alt="" for purely decorative ones.' });
  const dupAlt = [...groupBy(imgs.filter(i => i.alt && i.alt.length > 3), i => i.alt.toLowerCase()).values()].filter(g => new Set(g.map(i => i.src)).size > 3);
  add({ id: 'img-alt-duplicate', severity: 'low', title: 'Same alt text reused on many different images', evidence: dupAlt.flatMap(g => g.slice(0, 5).map(i => ({ url: i.page, detail: `"${i.alt}" on ${new Set(g.map(x => x.src)).size} images` }))), why: 'Repeated alt text does not describe each image.', fix: 'Write alt text specific to each image.' });
  add({ id: 'img-alt-long', severity: 'low', title: 'Alt text over 125 characters', evidence: imgs.filter(i => i.alt && i.alt.length > 125).map(i => ({ url: i.page, detail: `${i.alt.length} chars on ${i.file}` })), why: 'Screen readers often cut off long alt text; it can read as stuffing.', fix: 'Keep alt text concise.' });
  add({ id: 'img-filename', severity: 'low', title: 'Images with non descriptive filenames', evidence: imgs.filter(i => i.file && /^(img|image|dsc|photo|screenshot|untitled|pxl|wp-image)?[_-]?\d{3,}|^[a-f0-9-]{20,}\./i.test(i.file)).map(i => ({ url: i.page, detail: i.file })), why: 'Filenames are a small relevance signal for image search.', fix: 'Name new uploads descriptively (spine-surgery-recovery.jpg).' });
  add({ id: 'img-dimensions', category: 'performance', severity: 'low', title: 'Images without width and height attributes', evidence: imgs.filter(i => i.src && (!i.width || !i.height) && i.ext !== 'svg').map(i => ({ url: i.page, detail: i.file || i.src })), why: 'Missing dimensions cause layout shift (CLS) while images load.', fix: 'Set width and height attributes or CSS aspect-ratio.' });
  add({ id: 'img-legacy-format', category: 'performance', severity: 'low', title: 'Images served only in JPEG or PNG', evidence: imgs.filter(i => ['jpg', 'jpeg', 'png'].includes(i.ext) && !i.inPicture).map(i => ({ url: i.page, detail: i.file })), why: 'WebP and AVIF are typically 25 to 50% smaller at the same quality.', fix: 'Serve WebP or AVIF versions (image CDN or optimization plugin).' });
  add({ id: 'img-no-lazy', category: 'performance', severity: 'low', title: 'Pages load many images without lazy loading', evidence: html.filter(p => p.data.images.length > 6 && p.data.images.filter(i => i.loading).length < p.data.images.length * 0.3).map(p => ({ url: p.finalUrl, detail: `${p.data.images.length} images, ${p.data.images.filter(i => i.loading).length} lazy` })), why: 'Offscreen images compete for bandwidth with what users see first.', fix: 'Add loading="lazy" to images below the fold (never the LCP image).' });
  add({ id: 'img-no-srcset', category: 'performance', severity: 'low', title: 'Large image sets without responsive srcset', evidence: html.filter(p => p.data.images.filter(i => i.src && i.ext !== 'svg').length >= 4 && !p.data.images.some(i => i.srcset)).map(p => ({ url: p.finalUrl, detail: `${p.data.images.length} images, none responsive` })), why: 'Phones download desktop sized images.', fix: 'Provide srcset and sizes.' });

  // Mobile (static signals)
  add({ id: 'viewport-missing', category: 'mobile', severity: 'high', title: 'Pages missing a mobile viewport tag', evidence: html.filter(p => !p.data.viewport).map(p => ({ url: p.finalUrl, detail: 'No meta viewport' })), why: 'Without it, phones render the desktop layout zoomed out. Google indexes the mobile version.', fix: 'Add <meta name="viewport" content="width=device-width, initial-scale=1">.' });
  add({ id: 'viewport-not-device-width', category: 'mobile', severity: 'medium', title: 'Viewport does not use device width', evidence: html.filter(p => p.data.viewport && !/width\s*=\s*device-width/i.test(p.data.viewport)).map(p => ({ url: p.finalUrl, detail: p.data.viewport })), why: 'Fixed width viewports do not adapt to screen size.', fix: 'Use width=device-width.' });
  add({ id: 'zoom-disabled', category: 'mobile', severity: 'low', title: 'Pinch zoom is disabled', evidence: html.filter(p => p.data.a11y.userScalableNo).map(p => ({ url: p.finalUrl, detail: p.data.viewport })), why: 'Blocking zoom hurts readability and accessibility.', fix: 'Remove user-scalable=no and maximum-scale=1.' });

  // International
  const hl = html.filter(p => p.data.hreflang.length);
  const intl = { pagesWithHreflang: hl.length, languages: [...new Set(hl.flatMap(p => p.data.hreflang.map(h => h.lang)))], htmlLang: [...new Set(html.map(p => p.data.lang).filter(Boolean))] };
  add({ id: 'lang-missing', category: 'accessibility', severity: 'low', title: 'Pages without an html lang attribute', evidence: html.filter(p => !p.data.lang).map(p => ({ url: p.finalUrl, detail: 'No lang on <html>' })), why: 'Language declarations help screen readers and language targeting.', fix: 'Set <html lang="en"> (or the right language).' });
  if (hl.length) {
    const byUrl = new Map(html.map(p => [p.finalUrl, p]));
    const valid = /^(x-default|[a-z]{2,3}(-[a-z0-9]{2,4})?)$/;
    add({ id: 'hreflang-invalid-code', category: 'international', severity: 'medium', title: 'Invalid hreflang codes', evidence: hl.flatMap(p => p.data.hreflang.filter(h => !valid.test(h.lang) || /^en-uk$/.test(h.lang)).map(h => ({ url: p.finalUrl, detail: h.lang }))), why: 'Invalid codes are ignored.', fix: 'Use ISO 639-1 language with optional ISO 3166-1 region (en-GB, not en-UK).' });
    add({ id: 'hreflang-no-self', category: 'international', severity: 'low', title: 'hreflang sets missing a self reference', evidence: hl.filter(p => !p.data.hreflang.some(h => h.href === p.finalUrl)).map(p => ({ url: p.finalUrl, detail: 'Page not listed in its own hreflang set' })), why: 'Each page should include itself in its hreflang annotations.', fix: 'Add a self referencing hreflang.' });
    add({ id: 'hreflang-no-return', category: 'international', severity: 'medium', title: 'hreflang alternates without return links', evidence: hl.flatMap(p => p.data.hreflang.filter(h => byUrl.has(h.href) && h.href !== p.finalUrl && !byUrl.get(h.href).data.hreflang.some(x => x.href === p.finalUrl)).map(h => ({ url: p.finalUrl, detail: `${h.href} does not link back` }))), why: 'Google ignores hreflang pairs that are not reciprocal.', fix: 'Make every alternate list all others, including itself.' });
    add({ id: 'hreflang-no-xdefault', category: 'international', severity: 'low', title: 'hreflang sets without x-default', evidence: hl.filter(p => !p.data.hreflang.some(h => h.lang === 'x-default')).map(p => ({ url: p.finalUrl, detail: 'No x-default' })), why: 'x-default tells Google which version to show unmatched users.', fix: 'Add an x-default alternate.' });
    add({ id: 'hreflang-canonical-conflict', category: 'international', severity: 'medium', title: 'hreflang on pages that canonicalize elsewhere', evidence: hl.filter(p => p.indexability.canonical && !p.indexability.canonical.self).map(p => ({ url: p.finalUrl, detail: `Canonical ${p.indexability.canonical.target}` })), why: 'hreflang should only reference canonical URLs.', fix: 'Align canonical and hreflang URLs.' });
  }

  // Accessibility (secondary)
  add({ id: 'a11y-form-labels', category: 'accessibility', severity: 'low', title: 'Form fields without labels', evidence: html.filter(p => p.data.a11y.unlabeledInputs).map(p => ({ url: p.finalUrl, detail: `${p.data.a11y.unlabeledInputs} of ${p.data.a11y.inputs} fields` })), why: 'Unlabeled fields are unusable with screen readers and reduce form completions.', fix: 'Associate a <label> or aria-label with every field.' });
  add({ id: 'a11y-empty-links', category: 'accessibility', severity: 'low', title: 'Links and buttons without accessible text', evidence: html.filter(p => p.data.a11y.emptyLinks || p.data.a11y.emptyButtons).map(p => ({ url: p.finalUrl, detail: `${p.data.a11y.emptyLinks} links, ${p.data.a11y.emptyButtons} buttons` })), why: 'Icon only controls are announced as "link" with no purpose.', fix: 'Add visible text or aria-label.' });
  add({ id: 'a11y-no-main', category: 'accessibility', severity: 'low', title: 'Pages without a main landmark', evidence: html.filter(p => !p.data.a11y.hasMainLandmark).map(p => ({ url: p.finalUrl, detail: 'No <main>' })), why: 'Landmarks let assistive tech jump to the content and help parsers find the main text.', fix: 'Wrap primary content in <main>.' });
  add({ id: 'a11y-aria-role', category: 'accessibility', severity: 'low', title: 'Unknown ARIA roles or positive tabindex', evidence: html.filter(p => p.data.a11y.invalidAria || p.data.a11y.positiveTabindex).map(p => ({ url: p.finalUrl, detail: `${p.data.a11y.invalidAria} unknown roles, ${p.data.a11y.positiveTabindex} positive tabindex` })), why: 'Invalid ARIA and custom tab orders break keyboard navigation.', fix: 'Use valid roles and natural tab order.' });

  const a11yChecks = html.map(p => { const a = p.data.a11y; let s = 100; if (!p.data.lang) s -= 10; if (a.unlabeledInputs) s -= 15; if (a.emptyLinks + a.emptyButtons) s -= Math.min(20, (a.emptyLinks + a.emptyButtons) * 3); if (!a.hasMainLandmark) s -= 8; if (p.data.images.some(i => !i.hasAlt)) s -= 15; if (a.invalidAria || a.positiveTabindex) s -= 7; if (a.userScalableNo) s -= 10; if (p.data.headings.some((h, i, arr) => i && h.level - arr[i - 1].level > 1)) s -= 5; return Math.max(0, s); });
  const data = {
    brandSuffix: brand, international: intl,
    accessibilityScore: a11yChecks.length ? Math.round(a11yChecks.reduce((a, b) => a + b, 0) / a11yChecks.length) : null,
    titleStats: { withTitle: titles.length, avgLength: titles.length ? Math.round(titles.reduce((a, t) => a + t.length, 0) / titles.length) : 0 },
    imageStats: { total: imgs.length, missingAlt: imgs.filter(i => !i.hasAlt).length, emptyAlt: imgs.filter(i => i.alt === '').length, modernFormat: imgs.filter(i => ['webp', 'avif', 'svg'].includes(i.ext)).length, lazy: imgs.filter(i => i.loading).length, withDimensions: imgs.filter(i => i.width && i.height).length },
    social: { withOg: html.filter(p => p.data.og.title && p.data.og.image).length, withTwitter: html.filter(p => p.data.twitter.card).length, homeOg: html.find(p => p.finalUrl === homeUrl)?.data.og || null },
  };
  return { data, issues };
}
